name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

#  deploy:
#    needs:
#      - release-please
#    if: needs.release-please.outputs.released
#    runs-on: ubuntu-latest
#    steps:
#      - run: wget ${{ secrets.DEPLOY_SCRIPT_URL }}
